apiVersion: v1
kind: Service
metadata:
  name: moodle-d
  labels:
    app: moodle-d
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: moodle-d
    tier: frontend